name: Run Xray

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

- name: Install Xray
  run: |
    curl -L -o xray.tar.gz https://github.com/XTLS/Xray-core/releases/download/v1.9.0/xray-linux-amd64-v1.9.0.tar.gz
    tar -xzvf xray.tar.gz
    sudo mv xray /usr/local/bin/
    sudo chmod +x /usr/local/bin/xray
    
    - name: Run Xray
      run: |
        xray -c config.json
