name: Run Xray

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar curl

    - name: Download Xray
      run: |
        wget https://github.com/Rerechan-Store/Rerechan-Store/raw/main/xray
  
    - name: Move Xray Binary
      run: |
        sudo mv xray /usr/local/bin/
        sudo chmod +x /usr/local/bin/xray

    - name: List Files
      run: |
        ls -l
        touch xray.log

    - name: Run Xray in Background
      run: |
        nohup xray -c config.json > xray.log 2>&1 &

    - name: Verify Xray is Running
      run: |
        ps aux | grep xray

    - name: Get Runner IP
      run: |
        curl -s ifconfig.me
